# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Draft Games' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Draft Games
    pod 'SwiftyJSON', '~> 4.0'



  
  
  

  target 'Draft GamesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Draft GamesUITests' do
    # Pods for testing
  end

end
